//
// Copyright(C) 2019-2026, Daniel M. Porrey. All rights reserved.
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Diamond.Core.Workflow
{
	/// <summary>
	/// Provides functionality to retrieve and manage workflow items using dependency injection and logging services.
	/// </summary>
	/// <remarks>The factory uses the provided service provider to resolve workflow item collections based on a
	/// service key. Logging is performed for workflow item discovery and processing. This class is intended to be used as
	/// a base for custom workflow item factories and supports extensibility through virtual members.</remarks>
	public class WorkflowItemFactory : IWorkflowItemFactory
	{
		/// <summary>
		/// Initializes a new instance of the WorkflowItemFactory class using the specified service provider.
		/// </summary>
		/// <param name="serviceProvider">The service provider used to resolve dependencies required by the factory. Cannot be null.</param>
		public WorkflowItemFactory(IServiceProvider serviceProvider)
		{
			this.ServiceProvider = serviceProvider;
		}

		/// <summary>
		/// Initializes a new instance of the WorkflowItemFactory class using the specified service provider and logger.
		/// </summary>
		/// <param name="serviceProvider">The service provider used to resolve dependencies required by the factory.</param>
		/// <param name="logger">The logger used to record diagnostic and operational information for the factory.</param>
		public WorkflowItemFactory(ILogger<WorkflowItemFactory> logger, IServiceProvider serviceProvider)
			: this(serviceProvider)
		{
			this.Logger = logger;
		}

		/// <summary>
		/// Gets or sets the service provider used to resolve service dependencies within the class.
		/// </summary>
		/// <remarks>Assigning a custom service provider allows for advanced dependency injection scenarios or
		/// integration with external service containers.</remarks>
		protected virtual IServiceProvider ServiceProvider { get; set; }

		/// <summary>
		/// Gets or sets the logger instance used for logging workflow item factory operations.
		/// </summary>
		/// <remarks>Assign a custom logger to capture log messages generated by the workflow item factory. By
		/// default, logging is disabled unless a logger is provided.</remarks>
		public virtual ILogger<WorkflowItemFactory> Logger { get; set; } = new NullLogger<WorkflowItemFactory>();

		/// <summary>
		/// Asynchronously retrieves workflow items associated with the specified service key.
		/// </summary>
		/// <remarks>Only items that implement the IWorkflowItem interface and match the expected type are included in
		/// the result. Items that do not match are disposed if possible.</remarks>
		/// <param name="serviceKey">The unique key identifying the service for which workflow items are requested. Cannot be null or empty.</param>
		/// <returns>A task that represents the asynchronous operation. The task result contains a collection of workflow items
		/// matching the specified service key.</returns>
		/// <exception cref="Exception">Thrown if no workflow items have been configured for the specified service key.</exception>
		public virtual Task<IEnumerable<IWorkflowItem>> GetItemsAsync(string serviceKey)
		{
			IList<IWorkflowItem> returnValue = [];

			//
			// Find the repository that supports the given type.
			//
			IEnumerable<IWorkflowItem> items = this.ServiceProvider.GetKeyedService<IEnumerable<IWorkflowItem>>(serviceKey);
			this.Logger.LogDebug("Found {count} workflow items for Service Key '{serviceKey}'.", items.Count(), serviceKey);

			if (items.Any())
			{
				this.Logger.LogDebug("Loading workflow items for Service Key '{serviceKey}'.", serviceKey);

				//
				// Get the type being requested.
				//
				Type targetType = typeof(IWorkflowItem);

				foreach (IWorkflowItem item in items)
				{
					if (targetType.IsInstanceOfType(item))
					{
						returnValue.Add(item);
						this.Logger.LogDebug("Added workflow item '{name}'.", item.Name);
					}
					else
					{
						this.Logger.LogDebug("Skipping workflow item '{name}' because it does not have the correct Type.", item.Name);

						//
						// Dispose the item (if it supports it).
						//
						this.Logger.LogDebug("Attempting to dispose unused item '{name}'.", item.Name);
						item.TryDispose();
					}
				}
			}
			else
			{
				//
				// No items
				//
				this.Logger.LogError("Work flow items for Service Key '{serviceKey}' have not been configured.", serviceKey);
				throw new Exception($"Work flow items for Service Key '{serviceKey}' have not been configured.");
			}

			return Task.FromResult<IEnumerable<IWorkflowItem>>(returnValue);
		}
	}
}
